Models/Domain/ServiceOption.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YardLad.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOption
    {
        public ServiceOption()
        {
            this.ServiceOptionItems = new HashSet<ServiceOptionItem>();
            this.ServiceOptionItems1 = new HashSet<ServiceOptionItem>();
        }
    
        public int ServiceOptionId { get; set; }
        public int ServiceId { get; set; }
        public Nullable<int> Order { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Service Service1 { get; set; }
        public virtual ICollection<ServiceOptionItem> ServiceOptionItems { get; set; }
        public virtual ICollection<ServiceOptionItem> ServiceOptionItems1 { get; set; }
    }
}

Models/View/ServiceOptionViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using YardLad.Models.Domain;

namespace YardLad.Models.View
{
    public class ServiceOptionCreateViewModel
    {
        public int ServiceId { get; set; }
        public Service Service { get; set; }
        public List<ServiceOption> ServiceOptions { get; set; }
    }
}

Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using YardLad.Models;
using YardLad.Models.Domain;
using YardLad.Models.Interfaces;
using YardLad.Models.View;

namespace YardLad.Controllers
{
    public class AdminController : Controller
    {
        private static readonly log4net.ILog _logger = log4net.LogManager.GetLogger(typeof(AdminController));
        private YardLadDevSSEntities db = new YardLadDevSSEntities();

        //
        // GET: /Admin/ControlPanel

        [Authorize(Roles = "admin")]
        public ActionResult ControlPanel()
        {
            var user = Membership.GetUser();
            var userId = (int)user.ProviderUserKey;
            var userProfile = db.UserProfiles.Where(up => up.UserId == userId).Single();

            ViewBag.NewContractors = db.Contractors.Where(c => c.DateCreated > userProfile.LastLoginDate).Count();
            ViewBag.NewUploadedQualifications = db.Qualifications.Where(q => q.DateSubmitted > userProfile.LastLoginDate).Count();
            ViewBag.NewServiceOptionRequests = db.ServiceOptionRequests.Where(sor => sor.DateRequested > userProfile.LastLoginDate).Count();
            ViewBag.NewServiceOptionItemRequests = db.ServiceOptionItemRequests.Where(soir => soir.DateRequested > userProfile.LastLoginDate).Count();

            return View();
        }

        //
        // GET: /Admin/Contact
        
        public ActionResult Contact(string returnUrl, string subject = "")
        {
            // get the current user
            var user = Membership.GetUser();
            var userId = (int)user.ProviderUserKey;
            var userProfile = db.UserProfiles.Where(up => up.UserId == userId).Single();
            string name = userProfile.FirstName + " " + userProfile.LastName;

            ContactAdminViewModel model = new ContactAdminViewModel()
            {
                Name = name,
                Email = user.Email,
            };

            if (subject != null && subject != "")
            {
                model.Subject = subject;
            }

            // check roles
            if (Roles.IsUserInRole("contractor") || Roles.IsUserInRole("contractor2"))
            {
                model.IsContractor = true;

                // look up the contractor information
                var contractorUser = db.ContractorUsers.Where(cu => cu.UserId == userId).Single();

                model.TypeOfBusiness = contractorUser.Contractor.ContractorType.Type;
                model.BusinessName = contractorUser.Contractor.Name;
                model.BusinessPhone = userProfile.Phone;
                model.Roles = Roles.GetRolesForUser(user.UserName);
            }

            if (returnUrl != null)
            {
                model.ReturnUrl = returnUrl;
            }

            return View(model);
        }

        //
        // POST: Admin/Contact

        [HttpPost]
        public ActionResult Contact(ContactAdminViewModel model)
        {
            // setup email
            IEmailSender sender = new GoDaddyEmailSender();
            string subject = null;

            if (model.Subject != null)
            {
                subject = model.Subject;
            }
            else
	        {
                subject = "No Subject";
	        }

            string body = null;

            if (model.IsContractor != true)
            {
                body = string.Format("<p>New contact form submission!</p>" + "<p>Name: {0}<br />Email: {1}<br />"
                + "Message: {2}</p>", model.Name, model.Email, model.Message);
            }
            else // is a contractor
            {
                string roles = null;

                if (model.Roles.Count() > 1)
                {
                    for (int i = 0; i < model.Roles.Length; i++)
                    {
                        roles += model.Roles[i] + ",";
                    }
                }
                else
                {
                    roles = model.Roles[0];
                }

                body = string.Format("<p>New contact form submission!</p>" + "<p>Name: {0}<br />Email: {1}<br />Contractor Type: {2}<br />"
                + "Business Name: {3}<br />Business Phone: {4}<br />Roles: {5}<br />Message: {6}</p>", 
                model.Name, model.Email, model.TypeOfBusiness, model.BusinessName, model.BusinessPhone, roles, model.Message);
            }

            // the db contact email is pulled from the site settings
            var contactEmail = db.SiteSettings.Where(ss => ss.Name == "Yard Lad Contact Email").Single().Value;

            try
            {
                // try to send the email
                sender.SendEmail(model.Subject, body, from: contactEmail, recipient: contactEmail);
            }
            catch (Exception ex)
            {
                _logger.Error("there was an error sending the contact email to the admin from " + model.Name, ex);
            }

            // let the user know that their message was sent
            return View("Submitted", model);
        }

        public ActionResult Submitted()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Controllers/ServiceOptionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YardLad.Models.Domain;
using YardLad.Models.View;

namespace YardLad.Controllers
{
    [Authorize(Roles = "admin")]
    public class ServiceOptionController : Controller
    {
        private YardLadDevSSEntities db = new YardLadDevSSEntities();

        //
        // GET: /ServiceOption/

        public ViewResult Index(int id)
        {
            // service options are for a particular service, the service id will need to be passed to the controller here
            // look up the service options under that particular service
            var serviceOptions = db.ServiceOptions.Where(so => so.ServiceId == id).Include(s => s.ServiceOptionItems).Include(s => s.Service);
            ViewBag.Service = db.Services.Where(s => s.ServiceId == id).Single(); // used to display any necessary service info (ex. Name)
            return View(serviceOptions.ToList());
        }

        //
        // GET: /ServiceOption/Details/5

        public ViewResult Details(int id)
        {
            ServiceOption serviceoption = db.ServiceOptions.Find(id);
            ViewBag.ServiceOptionItems = db.ServiceOptionItems.ToList();
            return View(serviceoption);
        }

        //
        // GET: /ServiceOption/Create

        public ActionResult Create(int id)
        {
            ServiceOptionCreateViewModel model = new ServiceOptionCreateViewModel();
            model.ServiceId = id;
            model.Service = db.Services.Where(s => s.ServiceId == id).Single();
            model.ServiceOptions = new List<ServiceOption>();
            
            return View(model);
        }

        //
        // POST: /ServiceOption/Create

        [HttpPost]
        public ActionResult Create(ServiceOptionCreateViewModel model)
        {
            foreach (var serviceOption in model.ServiceOptions)
            {
                if (serviceOption.Name == null)
                {
                    ModelState.AddModelError("", "each service option must have a name");
                    break;
                }
            }

            // if the service option already has an option of the same name, throw an error
            var currentServiceOptions = db.ServiceOptions.Where(so => so.ServiceId == model.ServiceId);

            foreach (var serviceOption in currentServiceOptions)
            {
                foreach (var so in model.ServiceOptions.Where(so => so.Name != null))
                {
                    if (serviceOption.Name.ToLower() == so.Name.ToLower())
                    {
                        ModelState.AddModelError("", "this option is already associated with this service");
                    }
                }
            }

            if (ModelState.IsValid)
            {
                var currentOptions = db.ServiceOptions.Where(so => so.ServiceId == model.ServiceId);

                // the user has already inserted service options
                if (currentOptions.Count() >= 1)
                {
                    var currentCount = currentOptions.Count();
                    for (int i = 1; i <= model.ServiceOptions.Count; i++)
                    {
                        var serviceOption = new ServiceOption()
                        {
                            IsActive = true,
                            Name = model.ServiceOptions[i - 1].Name,
                            Order = currentCount + i,
                            ServiceId = model.ServiceId,
                            DateCreated = DateTime.Now.AddHours(2)
                        };

                        db.ServiceOptions.Add(serviceOption);
                    }
                }

                // the user is inserting service options for the first time
                if (currentOptions.Count() == 0)
	            {
                    for (int i = 1; i <= model.ServiceOptions.Count; i++)
                    {
                        var serviceOption = new ServiceOption()
                        {
                            IsActive = true,
                            Name = model.ServiceOptions[i - 1].Name,
                            Order = i,
                            ServiceId = model.ServiceId,
                            DateCreated = DateTime.Now.AddHours(2)
                        };

                        db.ServiceOptions.Add(serviceOption);
                    }
                }

                db.SaveChanges();
                return RedirectToAction("Index", new { id = model.ServiceId });
            }

            model.Service = db.Services.Where(s => s.ServiceId == model.ServiceId).Single();
            return View(model);
        }

        //
        // GET: /ServiceOption/Edit/5

        public ActionResult Edit(int id)
        {
            ServiceOption serviceoption = db.ServiceOptions.Find(id);
            return View(serviceoption);
        }

        //
        // POST: /ServiceOption/Edit/5

        [HttpPost]
        public ActionResult Edit(ServiceOption model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = model.ServiceId });
            }

            return View(model);
        }

        //
        // GET: /ServiceOption/Delete/5

        public ActionResult Delete(int id)
        {
            ServiceOption serviceoption = db.ServiceOptions.Find(id);
            return View(serviceoption);
        }

        //
        // POST: /ServiceOption/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            // remove the service option
            ServiceOption serviceOption = db.ServiceOptions.Find(id);
            db.ServiceOptions.Remove(serviceOption);

            //remove all the service option items
            foreach (var serviceOptionItem in db.ServiceOptionItems.Where(soi => soi.ServiceOptionId == id))
            {
                db.ServiceOptionItems.Remove(serviceOptionItem);
            }

            db.SaveChanges();
            return RedirectToAction("Index", new { id = serviceOption.ServiceId });
        }

        public ActionResult Requests()
        {
            List<ServiceOptionRequest> requests = db.ServiceOptionRequests.ToList();
            return View(requests);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/ServiceOption/Create.cshtml
@model YardLad.Models.View.ServiceOptionCreateViewModel

@{
    ViewBag.Title = "Add Service Option";
}

<style>
    .validation-summary-errors ul {
        list-style: none;
        padding-left: 0;
    }
</style>

<script>
    $(document).ready(function () {

        // variable to hold the number of service options (initial value)
        var serviceOptionCount = $('.serviceOption').length;

        $("#add").click(function () {
            var arrayCount = serviceOptionCount; // used for the array index (used for model binding to list)
            // var orderNumber = serviceOptionCount + 1; // don't need this, will be calculated based on order in the list (top to bottom)

            // add a service option at the bottom of the service option list
            $(".serviceOption:last-of-type").after('<div class="serviceOption"><div class="editor-field">'
                + '<input type="text" name="ServiceOptions[' + arrayCount + '].Name" id="ServiceOptions[' + arrayCount + '].Name" value="" />'
                + '<input type="hidden" name="ServiceOptions[' + arrayCount + '].ServiceId" id="ServiceOptions[' + arrayCount + '].ServiceId" value="@Model.ServiceId" />'
                + '<input type="hidden" name="ServiceOptions[' + arrayCount + '].IsActive" id="ServiceOptions[' + arrayCount + '].IsActive" value="true" />'
                + '<input type="button" class="remove" value="remove" style="margin-left: .25em;" />'
                + '</div></div>');

            // add one to the global variable
            serviceOptionCount += 1;

            // if the service option count is more than 1, change the submit button text (it will be)
            if (serviceOptionCount > 1) {
                $("#Submit").attr('value', 'Add Service Options');
            }
        });

        // the user clicks the remove button
        $('.remove').live('click', function () {
            $(this).parent().remove() // remove the parent element

            serviceOptionCount -= 1; // decrease the global variable by 1

            // if there is only one textbox for service area name, change the submit button text at the bottom
            if (serviceOptionCount == 1) {
                $("#Submit").attr('value', 'Add Service Option');
            }
        });

    });
</script>

<h2>Add Service Option | <span class="admin">@Html.ActionLink("back", "Index", new { id = Model.ServiceId }, new { @class = "admin" })</span></h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    @Html.HiddenFor(m => m.ServiceId)
    
    <div class="editor-label">
        @Html.LabelFor(m => m.ServiceId, "Service")
    </div>
    <div class="editor-field">
        @Html.DisplayFor(m => m.Service.Name)
    </div>

    <div id="newServiceOptions">
        <div class="editor-label">
            Service Option | <input id="add" type="button" value="add another" />
        </div>
        <div class="serviceOption">
            <div class="editor-field">
                <input type="text" name="ServiceOptions[0].Name" id="ServiceOptions[0].Name" value="" />
                <input type="hidden" name="ServiceOptions[0].Order" id="ServiceOptions[0].Order" value="1" />
                <input type="hidden" name="ServiceOptions[0].ServiceId" id="ServiceOptions[0].ServiceId" value="@Model.ServiceId" />
                <input type="hidden" name="ServiceOptions[0].IsActive" id="ServiceOptions[0].IsActive" value="true" />
                
            </div>
        </div>
    </div>
    <p>
        <input type="submit" id="Submit" value="Add Service Option" />
    </p>
}

Views/ServiceOption/Delete.cshtml
@model YardLad.Models.Domain.ServiceOption

@{
    ViewBag.Title = "Delete Service Option";
}

<script>
    $(document).ready(function () {
        var isConfirmed = false;

        $("form").submit(function (e) {
            if (!isConfirmed)
            {
                $("#dialog-confirm").dialog({
                    resizable: false,
                    height: 140,
                    modal: true,
                    buttons: {
                        "Yes": function () {
                            $(this).dialog("close");
                            isConfirmed = true;
                            $("form").submit();
                        },
                        Cancel: function () {
                            $(this).dialog("close");
                        }
                    }
                });

                e.preventDefault();
                return false;
            }
            else
            {
                return true;
            }
        });
      });
  </script>

<h2>Delete</h2>

<h3>Are you sure you want to delete this service option?</h3>

<div class="display-label">Service</div>
<div class="display-field">
    @Html.DisplayFor(m => m.Service.Name)
</div>

<div class="display-label">Option Name</div>
<div class="display-field">
    @Html.DisplayFor(m => m.Name)
</div>

<div class="display-label">Is Active</div>
<div class="display-field">
    @Html.DisplayFor(m => m.IsActive)
</div>

@using (Html.BeginForm()) {
    <p>
        <input type="submit" id="btnSubmit" value="Delete" />
    </p>
}

<div>
    @Html.ActionLink("Back", "Index", new { id = Model.ServiceId }, null)
</div>



<div id="dialog-confirm" title="Delete this service option?" class="hidden">
  <p>This service option will be permanently deleted. Are you sure?</p>
</div>

Views/ServiceOption/Details.cshtml
@model YardLad.Models.Domain.ServiceOption

@{
    ViewBag.Title = "Service Option Details";
}

<h2>Service Option Details | <span class="admin">@Html.ActionLink("back", "Index", new { id = Model.ServiceId }, new { @class = "admin" })</span></h2>

<div class="display-label">Service</div>
<div class="display-field">
    @Html.DisplayFor(m => m.Service.Name)
</div>

<div class="display-label">Option</div>
<div class="display-field">
    @Html.DisplayFor(m => m.Name)
</div>

<div class="display-label">
    Option Items
</div>

<div class="display-field" style="margin-top: 0; margin-bottom: 1em;">
        @foreach (var serviceOptionItem in ViewBag.ServiceOptionItems)
        {
            <div>
                @if (serviceOptionItem.ServiceOptionId == Model.ServiceOptionId)
                {
                    @serviceOptionItem.Name
                    <span style="color: orange; margin-left: .5em; font-weight: bold;">
                        @String.Format("{0:c}", serviceOptionItem.Price)
                    </span>
                }
            </div>
        }
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ServiceOptionId }, new { @class = "admin" })
    
</p>

Views/ServiceOption/Edit.cshtml
@model YardLad.Models.Domain.ServiceOption

@{
    ViewBag.Title = "Edit Service Option";
}

<h2>Edit Service Option | <span class="admin">@Html.ActionLink("delete", "Delete", "ServiceOption", new { id = Model.ServiceOptionId }, null)</span></h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

        @Html.HiddenFor(m => m.ServiceOptionId)
        @Html.HiddenFor(m => m.ServiceId)
        @Html.HiddenFor(m => m.DateCreated)

        <div class="editor-label">
            @Html.LabelFor(m => m.ServiceId, "Service")
        </div>
        <div class="editor-field">
            @Model.Service.Name
        </div>

        <div class="editor-label">
            <span style="width: 50px; display: inline-block;">@Html.LabelFor(m => m.Order, "Order")</span>
            <span>@Html.LabelFor(m => m.Name, "Option Name")</span>
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.Order, new { style = "width: 25px;" })
            @Html.TextBoxFor(m => m.Name)
        </div>
    
        <div class="editor-label">
            @Html.LabelFor(m => m.IsActive)
        </div>
        <div class="editor-field">
            @Html.CheckBoxFor(m => m.IsActive)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
}

<div>
    @Html.ActionLink("Back", "Index", new { id = Model.ServiceId }, new { @class = "admin" })
</div>

Views/ServiceOption/Index.cshtml
@model IEnumerable<YardLad.Models.Domain.ServiceOption>

@{
    ViewBag.Title = "Service Options";
}

<h2>Service Options  | <span class="admin">@Html.ActionLink("back", "Index", "Service", new { manage = "yes", mode = "all" }, null)</span></h2>

<p>
    @Html.ActionLink("Add New Service Option", "Create", new { id = ViewBag.Service.ServiceId }, new { @class = "admin" })
</p>

<div class="display-label">
    Service Name
</div>

<div class="display-field">
    @ViewBag.Service.Name
</div>


<div class="display-label">
    Service Options
</div>

@if (Model.Count() == 0)
{
    <p>no options have been added for this service</p>
}

@foreach (var serviceOption in Model.OrderBy(so => so.Order))
{
    <div class="display-field">
        @Html.DisplayFor(m => serviceOption.Order).
        @Html.ActionLink(serviceOption.Name, "Details", "ServiceOption", new { id = serviceOption.ServiceOptionId }, null)
        | <span class="admin">@Html.ActionLink("Edit", "Edit", "ServiceOption", new { id = serviceOption.ServiceOptionId }, null)</span>
        @if (serviceOption.ServiceOptionItems.Count == 0)
	    {
            @:| <span class="admin">@Html.ActionLink("Add Option Items", "Create", "ServiceOptionItem", new { id = serviceOption.ServiceOptionId }, null)</span>
	    }
        else
	    {
            @:| <span class="admin">@Html.ActionLink("View Option Items", "Index", "ServiceOptionItem", new { id = serviceOption.ServiceOptionId }, null)</span>
	    }
    </div>
}


@*@if (Model.Count() != 0)
{
    <table>
        <tr>
            <th></th>
            <th>
                Name
            </th>
            <th>
                Is Active
            </th>
            <th></th>
        </tr>

    @foreach (var serviceOption in Model.OrderBy(soi => soi.Order)) {
        <tr>
            <td>
                @Html.DisplayFor(soi => serviceOption.Order)
            </td>
            <td>
                @Html.ActionLink(serviceOption.Name, "Details", "ServiceOption", new { id = serviceOption.ServiceOptionId }, null)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(soi => serviceOption.IsActive)
            </td>
            <td>
                <span class="admin">@Html.ActionLink("Edit", "Edit", "ServiceOption", new { id = serviceOption.ServiceOptionId }, null)</span>
                @if (serviceOption.ServiceOptionItems.Count == 0)
	            {
                    @:| <span class="admin">@Html.ActionLink("Add Option Items", "Create", "ServiceOptionItem", new { id = serviceOption.ServiceOptionId }, null)</span>
	            }
                else
	            {
                    @:| <span class="admin">@Html.ActionLink("View Option Items", "Index", "ServiceOptionItem", new { id = serviceOption.ServiceOptionId }, null)</span>
	            }
            </td>
        </tr>
    }
    </table>
}
else
{
    <div>no option items have been provided</div>
}*@

Views/ServiceOption/Requests.cshtml
@model List<YardLad.Models.Domain.ServiceOptionRequest>

@{
    ViewBag.Title = "Service Option Requests";
}

<script>
    $(document).ready(function () {
        $(".accordion").accordion({ collapsible: true });
    });
</script>

@Html.ActionLink("back to Admin Control Panel", "ControlPanel", "Admin", null, new { @class = "admin" })
<h2>Service Option Requests</h2>

<p>
    This is the list of options that contractors have requested to be added
</p>

@if (Model.Count == 0)
{
    <div style="text-align: center;">No requests have been made...</div>
}

<div id="requestedServiceList" class="accordion">
    @foreach (var serviceOptionRequest in Model.OrderByDescending(sor => sor.DateRequested).ThenBy(sor => sor.Service.Name).ThenBy(sor => sor.Name))
    {
        <h3>@serviceOptionRequest.Service.Name <span style="float: right;">requested by @Html.ActionLink(serviceOptionRequest.Contractor.Name, "Details", "Contractor", new { id = serviceOptionRequest.ContractorId }, new { @class = "contractor", style = "color: cornflowerblue;" }) on @serviceOptionRequest.DateRequested.ToShortDateString() </span></h3>
        <div style="font-family: Georgia;">
            <div>@serviceOptionRequest.Name</div>
            <ol>
                @foreach (var serviceOptionItemRequest in serviceOptionRequest.ServiceOptionItemRequests.OrderBy(sor => sor.Order))
	            {
		            <li>@serviceOptionItemRequest.Name - @serviceOptionItemRequest.Price.ToString("c")</li>
	            }
            </ol>
            <div>
                @Html.ActionLink("Approve", "Approve", "ServiceOptionRequests", new { id = serviceOptionRequest.ServiceOptionRequestId }, new { style = "color: forestgreen;" }) | 
                @Html.ActionLink("Delete", "Delete", "ServiceOptionRequests", new { id = serviceOptionRequest.ServiceOptionRequestId },  new { style = "color: forestgreen;" })
            </div>
        </div>
    }

</div>