dev/Models/Domain/ServiceArea.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YardLad.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceArea
    {
        public ServiceArea()
        {
            this.Contractors = new HashSet<Contractor>();
            this.ContractorServiceAreas = new HashSet<ContractorServiceArea>();
        }
    
        public int ServiceAreaId { get; set; }
        public int StateId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Contractor> Contractors { get; set; }
        public virtual ICollection<ContractorServiceArea> ContractorServiceAreas { get; set; }
        public virtual State State { get; set; }
    }
}

dev/Models/View/ServiceAreaViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using YardLad.Models.Domain;

namespace YardLad.Models.View
{
    public class ServiceAreaEditViewModel
    {
        public Contractor Contractor { get; set; }
        public int ContractorId { get; set; }
        public int StateId { get; set; }
        public System.Nullable<int> ServiceAreaId { get; set; }
    }
}

dev/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using YardLad.Models;
using YardLad.Models.Domain;
using YardLad.Models.Interfaces;
using YardLad.Models.View;

namespace YardLad.Controllers
{
    public class AdminController : Controller
    {
        private static readonly log4net.ILog _logger = log4net.LogManager.GetLogger(typeof(AdminController));
        private YardLadEntities db = new YardLadEntities();

        //
        // GET: /Admin/ControlPanel

        [Authorize(Roles = "admin")]
        public ActionResult ControlPanel()
        {
            var user = Membership.GetUser();
            var userId = (int)user.ProviderUserKey;
            var userProfile = db.UserProfiles.Where(up => up.UserId == userId).Single();

            ViewBag.NewContractors = db.Contractors.Where(c => c.DateCreated > userProfile.LastLoginDate).Count();
            ViewBag.NewUploadedQualifications = db.Qualifications.Where(q => q.DateSubmitted > userProfile.LastLoginDate).Count();
            ViewBag.NewServiceOptionRequests = db.ServiceOptionRequests.Where(sor => sor.DateRequested > userProfile.LastLoginDate).Count();
            ViewBag.NewServiceOptionItemRequests = db.ServiceOptionItemRequests.Where(soir => soir.DateRequested > userProfile.LastLoginDate).Count();

            return View();
        }

        //
        // GET: /Admin/Contact
        
        public ActionResult Contact(string returnUrl, string subject = "")
        {
            // get the current user
            var user = Membership.GetUser();
            var userId = (int)user.ProviderUserKey;
            var userProfile = db.UserProfiles.Where(up => up.UserId == userId).Single();
            string name = userProfile.FirstName + " " + userProfile.LastName;

            ContactAdminViewModel model = new ContactAdminViewModel()
            {
                Name = name,
                Email = user.Email,
            };

            if (subject != null && subject != "")
            {
                model.Subject = subject;
            }

            // check roles
            if (Roles.IsUserInRole("contractor") || Roles.IsUserInRole("contractor2"))
            {
                model.IsContractor = true;

                // look up the contractor information
                var contractorUser = db.ContractorUsers.Where(cu => cu.UserId == userId).Single();

                model.TypeOfBusiness = contractorUser.Contractor.ContractorType.Type;
                model.BusinessName = contractorUser.Contractor.Name;
                model.BusinessPhone = userProfile.Phone;
                model.Roles = Roles.GetRolesForUser(user.UserName);
            }

            if (returnUrl != null)
            {
                model.ReturnUrl = returnUrl;
            }

            return View(model);
        }

        //
        // POST: Admin/Contact

        [HttpPost]
        public ActionResult Contact(ContactAdminViewModel model)
        {
            // setup email
            IEmailSender sender = new GoDaddyEmailSender();
            string subject = null;

            if (model.Subject != null)
            {
                subject = model.Subject;
            }
            else
	        {
                subject = "No Subject";
	        }

            string body = null;

            if (model.IsContractor != true)
            {
                body = string.Format("<p>New contact form submission!</p>" + "<p>Name: {0}<br />Email: {1}<br />"
                + "Message: {2}</p>", model.Name, model.Email, model.Message);
            }
            else // is a contractor
            {
                string roles = null;

                if (model.Roles.Count() > 1)
                {
                    for (int i = 0; i < model.Roles.Length; i++)
                    {
                        roles += model.Roles[i] + ",";
                    }
                }
                else
                {
                    roles = model.Roles[0];
                }

                body = string.Format("<p>New contact form submission!</p>" + "<p>Name: {0}<br />Email: {1}<br />Contractor Type: {2}<br />"
                + "Business Name: {3}<br />Business Phone: {4}<br />Roles: {5}<br />Message: {6}</p>", 
                model.Name, model.Email, model.TypeOfBusiness, model.BusinessName, model.BusinessPhone, roles, model.Message);
            }

            // the db contact email is pulled from the site settings
            var contactEmail = db.SiteSettings.Where(ss => ss.Name == "Yard Lad Contact Email").Single().Value;

            try
            {
                // try to send the email
                sender.SendEmail(model.Subject, body, from: contactEmail, recipient: contactEmail);
            }
            catch (Exception ex)
            {
                _logger.Error("there was an error sending the contact email to the admin from " + model.Name, ex);
            }

            // let the user know that their message was sent
            return View("Submitted", model);
        }

        public ActionResult Submitted()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

dev/Controllers/ServiceAreaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YardLad.Models.Domain;

namespace YardLad.Controllers
{
    public class ServiceAreaController : Controller
    {
        private YardLadEntities db = new YardLadEntities();

        //
        // GET: ServiceArea/Index

        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var model = db.ServiceAreas.OrderBy(sa => sa.State.Name).ThenBy(sa => sa.Name).ToList();

            return View(model);
        }

        //
        // GET: ServiceArea/Create

        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            ServiceArea model = new ServiceArea()
            {
                IsActive = true
            };

            ViewBag.State = new SelectList(db.States.Where(s => s.IsActive == true).OrderBy(x => x.Name), "StateId", "Name");

            return View(model);
        }

        //
        // POST: ServiceArea/Create

        [HttpPost]
        public ActionResult Create(ServiceArea model)
        {
            if (ModelState.IsValid)
            {
                db.ServiceAreas.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        //
        // GET: ServiceArea/Edit/5

        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            ServiceArea model = db.ServiceAreas.Where(sa => sa.ServiceAreaId == id).Single();
            
            ViewBag.State = new SelectList(db.States.Where(s => s.IsActive == true), "StateId", "Name");
            return View(model);
        }

        //
        // GET: ServiceArea/Edit/5

        [HttpPost]
        public ActionResult Edit(ServiceArea model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);

        }

        //
        // GET: ServiceArea/GetServiceAreasByState/5

        public JsonResult GetServiceAreasByState(int stateId)
        {
            var serviceAreas = db.ServiceAreas.Where(sa => sa.StateId == stateId).OrderBy(sa => sa.Name)
                .Select(x => new {
                    ServiceAreaId = x.ServiceAreaId,
                    Name = x.Name
                }).ToList();

            return this.Json(serviceAreas, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: ServiceArea/GetSecondaryServiceAreasByState/

        public JsonResult GetSecondaryServiceAreasByState(int stateId, int contractorId)
        {
            // the contractor who is going to add a secondary service area
            var contractor = db.Contractors.Where(c => c.ContractorId == contractorId).Single();

            // the primary service area id on the contractor account
            var primaryServiceAreaId = contractor.ServiceAreaId;

            // the list of secondary contractor service areas currently in the database
            var contractorServiceAreas = db.ContractorServiceAreas.Where(csa => csa.ContractorId == contractorId);
            HashSet<int> serviceAreaIds = new HashSet<int>(contractorServiceAreas.Select(x => x.ServiceAreaId));
            
            // data to send back to page (as ddl)
            var serviceAreas = db.ServiceAreas.Where(sa => sa.ServiceAreaId != primaryServiceAreaId)
                .Where(sa => sa.StateId == stateId).OrderBy(sa => sa.Name)
                .Select(x => new
                {
                    ServiceAreaId = x.ServiceAreaId,
                    Name = x.Name
                }).ToList();

            // remove any secondary contractor services that have already been added in the db from the results
            serviceAreas.RemoveAll(x => serviceAreaIds.Contains(x.ServiceAreaId));

            return this.Json(serviceAreas, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

dev/Views/ServiceArea/Create.cshtml
@model YardLad.Models.Domain.ServiceArea

@{
    ViewBag.Title = "Add Service Area";
}

<h2>Add Service Area | <span class="admin">@Html.ActionLink("back", "Index", "ServiceArea", null, new { @class = "admin" })</span></h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    @Html.HiddenFor(m => m.IsActive)

    <div class="editor-label">
        State
    </div>
    <div class="editor-field">
        @Html.DropDownListFor(m => m.StateId, (SelectList)ViewBag.State, "[ - select a state - ]")
        @Html.ValidationMessageFor(model => model.StateId)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Name)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
    </div>

    <p>
        <input type="submit" value="Create" />
    </p>
}

dev/Views/ServiceArea/Edit.cshtml
@model YardLad.Models.Domain.ServiceArea

@{
    ViewBag.Title = "Edit Service Area";
}

<h2>Edit Service Area | <span class="admin">@Html.ActionLink("back", "Index", null, new { @class = "admin" })</span></h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    @Html.HiddenFor(model => model.ServiceAreaId)

    <div class="editor-label">
        State
    </div>
    <div class="editor-field">
        @Html.DropDownListFor(m => m.StateId, (SelectList)ViewBag.State, "[ - select a state - ]")
        @Html.ValidationMessageFor(model => model.StateId)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Name)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.IsActive, "Is Active")
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.IsActive)
        @Html.ValidationMessageFor(model => model.IsActive)
    </div>

    <p>
        <input type="submit" value="Save" />
    </p>
}

dev/Views/ServiceArea/Index.cshtml
@model IEnumerable<YardLad.Models.Domain.ServiceArea>

@{
    ViewBag.Title = "Service Areas";
}

@Html.ActionLink("back to Admin Control Panel", "ControlPanel", "Admin", null, new { @class = "admin" })
<h2>Service Areas</h2>

<p>
    @Html.ActionLink("Add New Service Area", "Create", "ServiceArea", null, new { @class = "admin" })
</p>
<table class="display dataTable">
    <thead>
        <tr>
            <th>
                State
            </th>
            <th>
                Name
            </th>
            <th>
                Is Active
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.State.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td style="text-align: right;">
                @Html.ActionLink("Edit Service Area", "Edit", new { id = item.ServiceAreaId }, new { @class = "admin" })
            </td>
        </tr>
    }
    </tbody>
</table>