dev/Models/Domain/Service.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YardLad.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.ContractorServices = new HashSet<ContractorService>();
            this.ServiceOptions = new HashSet<ServiceOption>();
            this.ServiceOptionRequests = new HashSet<ServiceOptionRequest>();
        }
    
        public int ServiceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ServiceCategoryId { get; set; }
        public decimal BasePrice { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ContractorService> ContractorServices { get; set; }
        public virtual ServiceCategory ServiceCategory { get; set; }
        public virtual ICollection<ServiceOption> ServiceOptions { get; set; }
        public virtual ICollection<ServiceOptionRequest> ServiceOptionRequests { get; set; }
    }
}

dev/Models/View/RequestServiceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using YardLad.Models.Domain;

namespace YardLad.Models.View
{
    public class RequestServiceViewModel
    {

        public State State { get; set; }

        public int StateId{get; set;}
        public string Name{get; set;}

        public Service Service { get; set; }
        public int ServiceId { get; set; }

        public ServiceArea ServiceArea { get; set; }
        public int ServiceArea { get; set; }
    }

    public class State
    { 
        
    }
}

dev/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using YardLad.Models;
using YardLad.Models.Domain;
using YardLad.Models.Interfaces;
using YardLad.Models.View;

namespace YardLad.Controllers
{
    public class AdminController : Controller
    {
        private static readonly log4net.ILog _logger = log4net.LogManager.GetLogger(typeof(AdminController));
        private YardLadEntities db = new YardLadEntities();

        //
        // GET: /Admin/ControlPanel

        [Authorize(Roles = "admin")]
        public ActionResult ControlPanel()
        {
            var user = Membership.GetUser();
            var userId = (int)user.ProviderUserKey;
            var userProfile = db.UserProfiles.Where(up => up.UserId == userId).Single();

            ViewBag.NewContractors = db.Contractors.Where(c => c.DateCreated > userProfile.LastLoginDate).Count();
            ViewBag.NewUploadedQualifications = db.Qualifications.Where(q => q.DateSubmitted > userProfile.LastLoginDate).Count();
            ViewBag.NewServiceOptionRequests = db.ServiceOptionRequests.Where(sor => sor.DateRequested > userProfile.LastLoginDate).Count();
            ViewBag.NewServiceOptionItemRequests = db.ServiceOptionItemRequests.Where(soir => soir.DateRequested > userProfile.LastLoginDate).Count();

            return View();
        }

        //
        // GET: /Admin/Contact
        
        public ActionResult Contact(string returnUrl, string subject = "")
        {
            // get the current user
            var user = Membership.GetUser();
            var userId = (int)user.ProviderUserKey;
            var userProfile = db.UserProfiles.Where(up => up.UserId == userId).Single();
            string name = userProfile.FirstName + " " + userProfile.LastName;

            ContactAdminViewModel model = new ContactAdminViewModel()
            {
                Name = name,
                Email = user.Email,
            };

            if (subject != null && subject != "")
            {
                model.Subject = subject;
            }

            // check roles
            if (Roles.IsUserInRole("contractor") || Roles.IsUserInRole("contractor2"))
            {
                model.IsContractor = true;

                // look up the contractor information
                var contractorUser = db.ContractorUsers.Where(cu => cu.UserId == userId).Single();

                model.TypeOfBusiness = contractorUser.Contractor.ContractorType.Type;
                model.BusinessName = contractorUser.Contractor.Name;
                model.BusinessPhone = userProfile.Phone;
                model.Roles = Roles.GetRolesForUser(user.UserName);
            }

            if (returnUrl != null)
            {
                model.ReturnUrl = returnUrl;
            }

            return View(model);
        }

        //
        // POST: Admin/Contact

        [HttpPost]
        public ActionResult Contact(ContactAdminViewModel model)
        {
            // setup email
            IEmailSender sender = new GoDaddyEmailSender();
            string subject = null;

            if (model.Subject != null)
            {
                subject = model.Subject;
            }
            else
	        {
                subject = "No Subject";
	        }

            string body = null;

            if (model.IsContractor != true)
            {
                body = string.Format("<p>New contact form submission!</p>" + "<p>Name: {0}<br />Email: {1}<br />"
                + "Message: {2}</p>", model.Name, model.Email, model.Message);
            }
            else // is a contractor
            {
                string roles = null;

                if (model.Roles.Count() > 1)
                {
                    for (int i = 0; i < model.Roles.Length; i++)
                    {
                        roles += model.Roles[i] + ",";
                    }
                }
                else
                {
                    roles = model.Roles[0];
                }

                body = string.Format("<p>New contact form submission!</p>" + "<p>Name: {0}<br />Email: {1}<br />Contractor Type: {2}<br />"
                + "Business Name: {3}<br />Business Phone: {4}<br />Roles: {5}<br />Message: {6}</p>", 
                model.Name, model.Email, model.TypeOfBusiness, model.BusinessName, model.BusinessPhone, roles, model.Message);
            }

            // the db contact email is pulled from the site settings
            var contactEmail = db.SiteSettings.Where(ss => ss.Name == "Yard Lad Contact Email").Single().Value;

            try
            {
                // try to send the email
                sender.SendEmail(model.Subject, body, from: contactEmail, recipient: contactEmail);
            }
            catch (Exception ex)
            {
                _logger.Error("there was an error sending the contact email to the admin from " + model.Name, ex);
            }

            // let the user know that their message was sent
            return View("Submitted", model);
        }

        public ActionResult Submitted()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

dev/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using YardLad.Models;
using YardLad.Models.Domain;
using YardLad.Models.Interfaces;
using YardLad.Models.View;

namespace YardLad.Controllers
{
    public class ServiceController : Controller
    {
        private YardLadEntities db = new YardLadEntities();

        //
        // GET: /Service/

        public ActionResult Index(string manage = "", string mode = "", string type = "")
        {
            ViewBag.Content = db.Contents.ToList(); // for admin-editable content (used foreach loops in the view)

            // the view is rendered differently (admin control) if the manage and mode request parameters are supplied
            if (manage == "yes")
            {
                // default data source (only show admin service types, contractor types can be managed through each respective contractor)
                var serviceList = db.Services.Include("ServiceCategory").Where(s => s.IsActive == true)
                    .OrderBy(s => s.ServiceCategory.Name.Contains("Test"))
                    .ThenBy(s => s.ServiceCategory.Name.Contains("No Category"))
                    .ThenBy(s => s.ServiceCategory.Name)
                    .ThenBy(s => s.Name).ToList();

                if (mode == "all") 
                {
                    serviceList = db.Services.Include("ServiceCategory")
                    .OrderByDescending(s => s.IsActive)
                    .ThenBy(s => s.ServiceCategory.Name.Contains("Test"))
                    .ThenBy(s => s.ServiceCategory.Name.Contains("No Category"))
                    .ThenBy(s => s.ServiceCategory)
                    .ThenBy(s => s.Name).ToList();
                }

                return View(serviceList);

            }

            return View();
        }

        //
        // GET: /Service/Details

        public ActionResult Details(int id)
        {
            var service = db.Services.Where(s => s.ServiceId == id).Single();

            return View(service);
        }

        //
        // GET: /Service/Create

        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            // create model to send to the view
            ServiceViewModel model = new ServiceViewModel()
            {
                IsActive = false // set default
            };

            ViewBag.ServiceCategory = new SelectList(db.ServiceCategories.ToList(), "ServiceCategoryId", "Name");
            return View(model);
        }

        //
        // POST: /Service/Create

        [HttpPost]
        public ActionResult Create(ServiceViewModel model)
        {
            // create the new service
            Service newService = new Service()
            {
                Name = model.Name,
                Description = model.Description,
                IsActive = false, // make sure it is set to active
                ServiceCategoryId = model.ServiceCategoryId,
                BasePrice = model.BasePrice,
                DateCreated = DateTime.Now.AddHours(2)
            };

            if (ModelState.IsValid)
            {
                db.Services.Add(newService);
                db.SaveChanges();
                return RedirectToAction("Index", new { manage = "yes", mode = "all" });
            }
            else
            {
                ViewBag.ServiceCategory = new SelectList(db.ServiceCategories.ToList().OrderBy(sc => sc.Name), "ServiceCategoryId", "Name", model.ServiceCategoryId);
                return View(model);
            }
        }

        //
        // GET: /Service/Edit

        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            // lookup the service that will be edited
            var serviceToEdit = db.Services.Where(s => s.ServiceId == id).Single();

            // create the view model
            ServiceViewModel model = new ServiceViewModel()
            {
                ServiceId = id,
                Name = serviceToEdit.Name,
                Description = serviceToEdit.Description,
                BasePrice = serviceToEdit.BasePrice,
                ServiceCategoryId = serviceToEdit.ServiceCategoryId,
                IsActive = serviceToEdit.IsActive,
                ServiceOptions = db.ServiceOptions.Where(so => so.ServiceId == serviceToEdit.ServiceId).ToList(),
            };

            ViewBag.ServiceCategory = new SelectList(db.ServiceCategories, "ServiceCategoryId", "Name", model.ServiceCategoryId);
            return View(model);
        }

        //
        // POST: /Service/Edit

        [HttpPost]
        public ActionResult Edit(ServiceViewModel model)
        {
            // lookup the service that will be edited
            var serviceToEdit = db.Services.Where(s => s.ServiceId == model.ServiceId).Single();

            if (ModelState.IsValid)
            {
                // update that service
                serviceToEdit.Name = model.Name;
                serviceToEdit.Description = model.Description;
                serviceToEdit.ServiceCategoryId = model.ServiceCategoryId;
                serviceToEdit.IsActive = model.IsActive;
                serviceToEdit.BasePrice = model.BasePrice;

                // save changes
                db.Entry(serviceToEdit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { manage = "yes", mode = "all" });
            }

            ViewBag.ServiceCategory = new SelectList(db.ServiceCategories, "ServiceCategoryId", "Name", model.ServiceCategoryId);
            return View(model);
        }

        //
        // GET: /Service/Activate

        [Authorize(Roles = "admin")]
        public ActionResult Activate(int id)
        {
            Service serviceToActivate = db.Services.Where(s => s.ServiceId == id).Single();
            return View(serviceToActivate);
        }

        //
        // POST: /Service/Activate

        [HttpPost, ActionName("Activate")]
        public ActionResult ActivateConfirm(int id)
        {
            Service serviceToActivate = db.Services.Where(s => s.ServiceId == id).Single();
            serviceToActivate.IsActive = true;

            db.Entry(serviceToActivate).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index", new { manage = "yes", mode = "all" });
        }

        //
        // GET: /Service/Deactivate

        [Authorize(Roles = "admin")]
        public ActionResult Deactivate(int id)
        {
            Service serviceToDeactivate = db.Services.Where(s => s.ServiceId == id).Single();
            return View(serviceToDeactivate);
        }

        //
        // POST: /Service/Deactivate

        [HttpPost, ActionName("Deactivate")]
        public ActionResult DeactivateConfirm(int id)
        {
            Service serviceToDeactivate = db.Services.Where(s => s.ServiceId == id).Single();
            serviceToDeactivate.IsActive = false;

            db.Entry(serviceToDeactivate).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index", new { manage = "yes", mode = "all" });
        }

        //
        // GET: /Service/Delete

        [Authorize(Roles = "admin")]
        public ActionResult Delete(int id)
        {
            Service serviceToDelete = db.Services.Where(s => s.ServiceId == id).Single();
            return View(serviceToDelete);
        }

        //
        // POST: /Service/Delete

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            var serviceToDelete = db.Services.Where(s => s.ServiceId == id).Single();

            // remove the service option items
            var serviceOptionItems = db.ServiceOptionItems.Where(soi => soi.ServiceOption.ServiceId == serviceToDelete.ServiceId);
            foreach (var serviceOptionItem in serviceOptionItems)
            {
                db.ServiceOptionItems.Remove(serviceOptionItem);
            }

            // remove the service options
            var serviceOptions = db.ServiceOptions.Where(so => so.ServiceId == serviceToDelete.ServiceId);
            foreach (var serviceOption in serviceOptions)
	        {
                db.ServiceOptions.Remove(serviceOption);
	        }

            // remove the service
            db.Services.Remove(serviceToDelete);

            // save all changes
            db.SaveChanges();
            return RedirectToAction("Index", new { manage = "yes", mode = "all" });
        }

        //
        // GET: /Service/RequestService

        public ActionResult RequestService()
        {
            int contractorServices = db.ContractorServices.Where(cs => cs.IsActive == true).Count();
            if (contractorServices == 0)
            {
                TempData["message"] = "We're sorry, there are currently no active contractors in the system to request services from. Please try again later.";
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        //
        // POST: /Service/RequestService

        [HttpPost]
        public ActionResult RequestService(RequestServiceViewModel model)
        {
            TempData["model"] = model;
            Session["RequestServiceViewModel"] = model;
            return RedirectToAction("SelectContractor");
        }

        //
        // GET: Service/SelectContractor/

        public ActionResult SelectContractor()
        {
            RequestServiceViewModel model = null;
            if (TempData["model"] != null)
            {
                model = (RequestServiceViewModel)TempData["model"];
            }
            else if (Session["RequestServiceViewModel"] != null)
            {
                model = (RequestServiceViewModel)Session["RequestServiceViewModel"];
            }

dev/Views/Service/Activate.cshtml
@model YardLad.Models.Domain.Service

@{
    ViewBag.Title = "Activate Service";
}

<h2>Activate Service | <span class="admin">@Html.ActionLink("back", "Index", new { manage = "yes", mode = "all" })</span></h2>
<h3>Are you sure you want to activate this service?</h3>

@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Activate" />
    </p>
}

dev/Views/Service/ContractorSubmitted.cshtml
@model YardLad.Models.View.ContractorUserViewModel

@{
    ViewBag.Title = "Form Submitted";
}

<p>Thank you for signing your business up with Yard Lad!<br />You can now view your account
    @Html.ActionLink("here", "MyAccount", "Account", null, new { @class = "contractor" }).
</p>

<p style="margin-bottom: .5em;">These are the next steps you will need to take before you can get started.</p>
<ul>
    <li>Submit your qualifications.</li>
    <li>Once submitted, an admin will review those qualifications and you will be notified when you are approved.</li>
    <li>Manage the services you or your company offer along with your pricing model (unless you accept our default pricing).</li>
    <li>Manage your tax rate information and the service area your company resides.</li>
    <li>Set your availability (days of the week available to do Yard Lad services).</li>
    <li>Before you can be listed, you will also need to submit payment.</li>
    <li>After payment is completed, selecting the "get listed" button on your account page will finalize your listing, and you will be notified when a customer requests a service from you or your company!</li>
</ul>

<p>
    Thank you for becoming a part of our network! If you have any questions or concerns please contact us.
    <br />-The Yard Lad team
</p>

dev/Views/Service/Create.cshtml
@model YardLad.Models.View.ServiceViewModel

@{
    ViewBag.Title = "Create Service";
}

<h2>New Service  | <span class="admin">@Html.ActionLink("Back", "Index", new { manage = "yes" })</span></h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    @Html.HiddenFor(m => m.IsActive)

    <div class="editor-label">
        @Html.LabelFor(m => m.ServiceCategoryId)
    </div>
    <div class="editor-field">
        @Html.DropDownListFor(m => m.ServiceCategoryId, (SelectList)ViewBag.ServiceCategory, "[ - select a category - ]")
        @Html.ValidationMessageFor(m => m.ServiceCategoryId)
    </div>
    
    <div class="editor-label">
        @Html.LabelFor(m => m.Name)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.Name)
        @Html.ValidationMessageFor(m => m.Name)
    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.Description)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.Description)
        @Html.ValidationMessageFor(m => m.Description)
    </div>
    
    
    
    <div class="editor-label">
        @Html.LabelFor(m => m.BasePrice)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.BasePrice)
        @Html.ValidationMessageFor(m => m.BasePrice)
    </div>

    <p>
        <input type="submit" value="Create" />
    </p>
}

dev/Views/Service/Deactivate.cshtml
@model YardLad.Models.Domain.Service

@{
    ViewBag.Title = "Deactivate Service";
}

<h2>Deactivate Service | <span class="admin">@Html.ActionLink("back", "Index", new { manage = "yes", mode = "all" })</span></h2>
<h3>Are you sure you want to deactivate this service?</h3>

@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Deactivate" />
    </p>
}

dev/Views/Service/Delete.cshtml
@model YardLad.Models.Domain.Service

@{
    ViewBag.Title = "Delete Service";
}

<script>
    $(document).ready(function () {
        var isConfirmed = false;

        $("form").submit(function (e) {
            if (!isConfirmed)
            {
                $("#dialog-confirm").dialog({
                    resizable: false,
                    height: 140,
                    modal: true,
                    buttons: {
                        "Yes": function () {
                            $(this).dialog("close");
                            isConfirmed = true;
                            $("#deleteService").submit();
                        },
                        Cancel: function () {
                            $(this).dialog("close");
                        }
                    }
                });

                e.preventDefault();
                return false;
            }
            else
            {
                return true;
            }
        });
    });
 </script>

<h2>Delete</h2>

<h3>Are you sure you want to delete this service?</h3>

<div class="display-label">Service Category</div>
<div class="display-field">
    @Html.DisplayFor(m => m.ServiceCategory.Name)
</div>

<div class="display-label">Name</div>
<div class="display-field">
    @Html.DisplayFor(m => m.Name)
</div>

<div class="display-label">Description</div>
<div class="display-field">
    @if (Model.Description == null)
    {
        @:No Description
    }
    else
    {
        @Html.DisplayFor(m => m.Description)
    }
    
</div>

<div class="display-label">Base Price</div>
<div class="display-field">
    @Html.DisplayFor(m => m.BasePrice)
</div>

<div class="display-label">Is Active</div>
<div class="display-field">
    @Html.DisplayFor(m => m.IsActive)
</div>

@using (Html.BeginForm("Delete", "Service", null, FormMethod.Post, new { id = "deleteService" }))
{
    <p>
        <input type="submit" id="btnSubmit" value="Delete" />
    </p>
}

<div>
    @Html.ActionLink("Back", "Index", new { manage = "yes" })
</div>


<div id="dialog-confirm" title="Delete this service?" class="hidden">
  <p>This service will be permanently deleted and cannot be recovered. Are you sure?</p>
</div>

dev/Views/Service/Edit.cshtml
@model YardLad.Models.View.ServiceViewModel

@{
    ViewBag.Title = "Edit Service";
}

<h2>
    Edit Service |
    <span class="admin">
        @Html.ActionLink("delete Service", "Delete", "Service", new { id = Model.ServiceId }, null)
    </span>
</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    @Html.HiddenFor(m => m.ServiceId)
    @Html.HiddenFor(m => m.ServiceCategoryId)
    @Html.HiddenFor(m => m.IsActive)

    <div class="editor-label">
        @Html.LabelFor(m => m.ServiceCategoryId)
    </div>
    <div class="editor-field">
        @Html.DropDownListFor(m => m.ServiceCategoryId, (SelectList)ViewBag.ServiceCategory)
        @Html.ValidationMessageFor(m => m.ServiceCategoryId)
    </div>
    
    <div class="editor-label">
        @Html.LabelFor(m => m.Name)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.Name)
        @Html.ValidationMessageFor(m => m.Name)
    </div>

    <div class="editor-label">
        @Html.LabelFor(m => m.Description)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.Description)
        @Html.ValidationMessageFor(m => m.Description)
    </div>
    
    <div class="editor-label">
        @Html.LabelFor(m => m.BasePrice)
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.BasePrice)
        @Html.ValidationMessageFor(m => m.BasePrice)
    </div>

    <p>
        <input type="submit" value="Save" />
    </p>
}

<div>
    @Html.ActionLink("Back", "Index", new { manage = "yes"}, new { @class = "admin" })
</div>

dev/Views/Service/Index.cshtml
@model IEnumerable<YardLad.Models.Domain.Service>
@{
    if (Request["manage"] == "yes")
    {
        ViewBag.Title = "Admin Services";
    }
    else
    {
        ViewBag.Title = "Services";
    }
}

<script type="text/javascript">
    $(document).ready(function () {
        var tb = $(".seven_container").sevenslider({
            width: 450,
            height: 200,
            fullwidth: false,
            automation: true,
            autointerval: 3,
            progress: true,
            progresstype: 'linear',
            bullet: true,
            carousel: false,
            circular: true,
            responsive: true,
            swipe: true,
            keyboard: true,
            skin: "clean",
            lightbox: false,
            onanimstart: function () {
                //Your Code here
            },
            onanimend: function () {
                //Your Code here
            }
        });
    });
</script>

@if (User.IsInRole("admin") && Request["manage"] == "yes")
{
    @Html.ActionLink("back to Admin Control Panel", "ControlPanel", "Admin", null, new { @class = "admin" })
}

<h2>Yard Lad Services</h2>

@if (Request["manage"] != "yes")
{
    <div class="seven_container">
        <div id="seven_viewport">
            <div class="seven_slider">
                <div class="seven_slide"><a class="seven_slide_title">Landscape Design</a><img src="@Url.Content("~/Content/Images/ServiceSlider/landscape-design.png")" /></div>
                <div class="seven_slide"><a class="seven_slide_title">Lawn Care</a><img src="@Url.Content("~/Content/Images/ServiceSlider/lawn-care.jpg")" /></div>
                <div class="seven_slide"><a class="seven_slide_title">Tree Removal</a><img src="@Url.Content("~/Content/Images/ServiceSlider/tree-removal.jpg")" /></div>
                <div class="seven_slide"><a class="seven_slide_title">Snow Removal</a><img src="@Url.Content("~/Content/Images/ServiceSlider/snow-removal.jpg")" /></div>
            </div>
        </div>
        <a id="left_btn" class="seven_nav">Previous Slide</a>
        <a id="right_btn" class="seven_nav right_btn">Next Slide</a>
    </div>

    <div>
        <h3>Our Services Include:</h3>
        <ul id="serviceList">
            @foreach (var c in ViewBag.Content)
            {
                if (c.SectionName == "Service Index (Service List)")
                {
                    if (User.IsInRole("admin"))
                    {
                        @Html.ActionLink("Edit", "Edit", "Content", new { id = c.ContentId, returnUrl = "Service/Index" }, new { @class = "admin" })
                    }
                    
                    @Html.Raw(c.ContentBody)
                }
            }
        </ul>
    </div>

}
else
{
    <p>
        This is an administrators list of services. Once activated, these services can be selected by a contractor
        as a service that they offer. Set the base price, add the options, and option items as a part of the service before activating.
        Once a contractor adds a service, it copies the values entered under the specific service listed here.
        They will not be able to modify what is listed under the service, just the base price and the price for each option item.
    </p>
    <div>
        @Html.ActionLink("Create New Service", "Create", "Service", null, new { @class = "admin" })

        @if (Request["mode"] != "all")
        {
	        <span style="float: right;">@Html.ActionLink("show all services", "Index", "Service", new { manage = "yes", mode = "all" }, new { @class = "admin" })</span>
        }
        else
        {
	        <span style="float: right;">@Html.ActionLink("show only active services", "Index", "Service", new { manage = "yes", mode = "" }, new { @class = "admin" })</span>
        }
    </div>
    
        foreach (var service in Model)
        {
        <div class="display-label">
            @Html.ActionLink(service.Name, "Details", "Service", new { id = service.ServiceId }, null) | 
            <span class="admin">@Html.ActionLink("Edit", "Edit", "Service", new { id = service.ServiceId }, null)</span> |
            @if (service.ServiceOptions.Count == 0)
            {
                <span class="admin">@Html.ActionLink("Add Service Options", "Index", "ServiceOption", new { id = service.ServiceId }, null)</span> @:|
            }
            else if (service.ServiceOptions.Count > 0)
            {
                <span class="admin">@Html.ActionLink("View Service Options", "Index", "ServiceOption", new { id = service.ServiceId }, null)</span> @:|
            }
            <span class="admin">
                @if (service.IsActive == true)
                {
                    @Html.ActionLink("Deactivate", "Deactivate", new { id = service.ServiceId }, null)
                }
                else if (service.IsActive == false)
                {
                    @Html.ActionLink("Activate", "Activate", new { id = service.ServiceId }, null)
                }
            </span>
            <span style="float: right;">@Html.DisplayFor(s => service.IsActive)</span>
        </div>
        }

        if (Model.Count() == 0 && Request["mode"] == "all")
        {
        <div style="text-align: center; margin-top: 1em;">no services have been entered</div>
        }

        if (Model.Count() == 0 && Request["mode"] != "all")
        {
        <div style="text-align: center; margin-top: 1em;">there are no active services currently in the database</div>
    }
}