Models/Domain/ContractorServiceArea.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YardLad.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorServiceArea
    {
        public int ContractorServiceAreaId { get; set; }
        public int ContractorId { get; set; }
        public int ServiceAreaId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual Contractor Contractor1 { get; set; }
        public virtual ServiceArea ServiceArea { get; set; }
        public virtual ServiceArea ServiceArea1 { get; set; }
    }
}

Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using YardLad.Models;
using YardLad.Models.Domain;
using YardLad.Models.Interfaces;
using YardLad.Models.View;

namespace YardLad.Controllers
{
    public class AdminController : Controller
    {
        private static readonly log4net.ILog _logger = log4net.LogManager.GetLogger(typeof(AdminController));
        private YardLadDevSSEntities db = new YardLadDevSSEntities();

        //
        // GET: /Admin/ControlPanel

        [Authorize(Roles = "admin")]
        public ActionResult ControlPanel()
        {
            var user = Membership.GetUser();
            var userId = (int)user.ProviderUserKey;
            var userProfile = db.UserProfiles.Where(up => up.UserId == userId).Single();

            ViewBag.NewContractors = db.Contractors.Where(c => c.DateCreated > userProfile.LastLoginDate).Count();
            ViewBag.NewUploadedQualifications = db.Qualifications.Where(q => q.DateSubmitted > userProfile.LastLoginDate).Count();
            ViewBag.NewServiceOptionRequests = db.ServiceOptionRequests.Where(sor => sor.DateRequested > userProfile.LastLoginDate).Count();
            ViewBag.NewServiceOptionItemRequests = db.ServiceOptionItemRequests.Where(soir => soir.DateRequested > userProfile.LastLoginDate).Count();

            return View();
        }

        //
        // GET: /Admin/Contact
        
        public ActionResult Contact(string returnUrl, string subject = "")
        {
            // get the current user
            var user = Membership.GetUser();
            var userId = (int)user.ProviderUserKey;
            var userProfile = db.UserProfiles.Where(up => up.UserId == userId).Single();
            string name = userProfile.FirstName + " " + userProfile.LastName;

            ContactAdminViewModel model = new ContactAdminViewModel()
            {
                Name = name,
                Email = user.Email,
            };

            if (subject != null && subject != "")
            {
                model.Subject = subject;
            }

            // check roles
            if (Roles.IsUserInRole("contractor") || Roles.IsUserInRole("contractor2"))
            {
                model.IsContractor = true;

                // look up the contractor information
                var contractorUser = db.ContractorUsers.Where(cu => cu.UserId == userId).Single();

                model.TypeOfBusiness = contractorUser.Contractor.ContractorType.Type;
                model.BusinessName = contractorUser.Contractor.Name;
                model.BusinessPhone = userProfile.Phone;
                model.Roles = Roles.GetRolesForUser(user.UserName);
            }

            if (returnUrl != null)
            {
                model.ReturnUrl = returnUrl;
            }

            return View(model);
        }

        //
        // POST: Admin/Contact

        [HttpPost]
        public ActionResult Contact(ContactAdminViewModel model)
        {
            // setup email
            IEmailSender sender = new GoDaddyEmailSender();
            string subject = null;

            if (model.Subject != null)
            {
                subject = model.Subject;
            }
            else
	        {
                subject = "No Subject";
	        }

            string body = null;

            if (model.IsContractor != true)
            {
                body = string.Format("<p>New contact form submission!</p>" + "<p>Name: {0}<br />Email: {1}<br />"
                + "Message: {2}</p>", model.Name, model.Email, model.Message);
            }
            else // is a contractor
            {
                string roles = null;

                if (model.Roles.Count() > 1)
                {
                    for (int i = 0; i < model.Roles.Length; i++)
                    {
                        roles += model.Roles[i] + ",";
                    }
                }
                else
                {
                    roles = model.Roles[0];
                }

                body = string.Format("<p>New contact form submission!</p>" + "<p>Name: {0}<br />Email: {1}<br />Contractor Type: {2}<br />"
                + "Business Name: {3}<br />Business Phone: {4}<br />Roles: {5}<br />Message: {6}</p>", 
                model.Name, model.Email, model.TypeOfBusiness, model.BusinessName, model.BusinessPhone, roles, model.Message);
            }

            // the db contact email is pulled from the site settings
            var contactEmail = db.SiteSettings.Where(ss => ss.Name == "Yard Lad Contact Email").Single().Value;

            try
            {
                // try to send the email
                sender.SendEmail(model.Subject, body, from: contactEmail, recipient: contactEmail);
            }
            catch (Exception ex)
            {
                _logger.Error("there was an error sending the contact email to the admin from " + model.Name, ex);
            }

            // let the user know that their message was sent
            return View("Submitted", model);
        }

        public ActionResult Submitted()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using YardLad.Models;
using YardLad.Models.Domain;
using YardLad.Models.Interfaces;
using YardLad.Models.View;

namespace YardLad.Controllers
{
    public class ContactController : Controller
    {
        private YardLadDevSSEntities db = new YardLadDevSSEntities();

        //
        // GET: /Contact/

        public ActionResult Index()
        {
            ViewBag.Address = db.SiteSettings.Where(ss => ss.Name == "Yard Lad Address").Single().Value;
            ViewBag.Email = db.SiteSettings.Where(ss => ss.Name == "Yard Lad Contact Email").Single().Value;
            ViewBag.Phone = db.SiteSettings.Where(ss => ss.Name == "Yard Lad Phone Number").Single().Value;

            return View();
        }

        //
        // POST: /Contact/

        [HttpPost, HandleError]
        public ActionResult Index(ContactViewModel model)
        {
            // check to make sure that the length of the phone number entered is correct
            if (model.Area.Length != 3 || model.Prefix.Length != 3 || model.Suffix.Length != 4)
            {
                ModelState.AddModelError("", "please enter a valid phone number");
            }

            if (ModelState.IsValid)
            {
                // format the phone number that will be sent in the email
                model.Phone = "(" + model.Area + ") " + model.Prefix + "-" + model.Suffix;

                // send the email via GoDaddy (implementing IEmailSender interface)
                IEmailSender emailsender = new GoDaddyEmailSender();
                string body = string.Format("<p>New contact form submission!</p>" + "<p>Name: {0}<br />Email: {1}<br />Phone: {2}<br />"
                    + "Message: {3}</p>", model.Name, model.Email, model.Phone, model.Message);

                var contactEmail = db.SiteSettings.Where(ss => ss.Name == "Yard Lad Contact Email").Single().Value;

                try
                {
                    // send email to contact@yardlad.com (will need to replace the emails when deploying)
                    emailsender.SendEmail(model.Subject, body, from: contactEmail, recipient: contactEmail);
                }
                catch (SmtpFailedRecipientException)
                {
                    throw new Exception("Your email was not sent, please try again later.");
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }

                // let the user know that their message was sent
                return View("Submitted", model);
            }

            return View(model);
        }

        //
        // GET: /Contact/Submitted

        public ActionResult Submitted(ContactViewModel model)
        {
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Controllers/ContractorServiceAreaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YardLad.Models.Domain;

namespace YardLad.Controllers
{ 
    [Authorize]
    public class ContractorServiceAreaController : Controller
    {
        private YardLadDevSSEntities db = new YardLadDevSSEntities();

        //
        // GET: /ContractorServiceArea/

        public ViewResult Index(int id)
        {
            var contractorServiceAreas = db.ContractorServiceAreas
                .Include(c => c.Contractor).Include(c => c.ServiceArea)
                .Where(csa => csa.ContractorId == id)
                .OrderBy(csa => csa.ServiceArea.State.Name)
                .ThenBy(csa => csa.ServiceArea.Name);

            ViewBag.ContractorId = id;

            return View(contractorServiceAreas.ToList());
        }

        //
        // GET: /ContractorServiceArea/Create

        public ActionResult Create(int id)
        {
            ContractorServiceArea model = new ContractorServiceArea()
            {
                ContractorId = id,
                Price = 0.00M,
            };

            var primaryServiceAreaId = db.Contractors.Where(c => c.ContractorId == id).Single().ServiceAreaId;

            ViewBag.State = new SelectList(db.States.OrderBy(s => s.Name), "StateId", "Name");
            ViewBag.ServiceAreaId = new SelectList(db.ServiceAreas.Where(sa => sa.ServiceAreaId != primaryServiceAreaId), "ServiceAreaId", "Name");
            return View(model);
        } 

        //
        // POST: /ContractorServiceArea/Create

        [HttpPost]
        public ActionResult Create(ContractorServiceArea model)
        {
            if (ModelState.IsValid)
            {
                db.ContractorServiceAreas.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = model.ContractorId });  
            }

            ViewBag.ContractorId = new SelectList(db.Contractors, "ContractorId", "Name", model.ContractorId);
            ViewBag.ServiceAreaId = new SelectList(db.ServiceAreas, "ServiceAreaId", "Name", model.ServiceAreaId);
            return View(model);
        }
        
        //
        // GET: /ContractorServiceArea/Edit/5
 
        public ActionResult Edit(int id)
        {
            ContractorServiceArea contractorservicearea = db.ContractorServiceAreas.Find(id);
            ViewBag.ContractorId = new SelectList(db.Contractors, "ContractorId", "Name", contractorservicearea.ContractorId);
            ViewBag.ServiceAreaId = new SelectList(db.ServiceAreas, "ServiceAreaId", "Name", contractorservicearea.ServiceAreaId);
            return View(contractorservicearea);
        }

        //
        // POST: /ContractorServiceArea/Edit/5

        [HttpPost]
        public ActionResult Edit(ContractorServiceArea contractorservicearea)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contractorservicearea).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = contractorservicearea.ContractorId });  
            }
            ViewBag.ContractorId = new SelectList(db.Contractors, "ContractorId", "Name", contractorservicearea.ContractorId);
            ViewBag.ServiceAreaId = new SelectList(db.ServiceAreas, "ServiceAreaId", "Name", contractorservicearea.ServiceAreaId);
            return View(contractorservicearea);
        }

        //
        // GET: /ContractorServiceArea/Delete/5
 
        public ActionResult Delete(int id)
        {
            ContractorServiceArea contractorservicearea = db.ContractorServiceAreas.Find(id);
            return View(contractorservicearea);
        }

        //
        // POST: /ContractorServiceArea/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            ContractorServiceArea contractorservicearea = db.ContractorServiceAreas.Find(id);
            db.ContractorServiceAreas.Remove(contractorservicearea);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = contractorservicearea.ContractorId });  
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/ContractorServiceArea/Create.cshtml
@model YardLad.Models.Domain.ContractorServiceArea

@{
    ViewBag.Title = "Add Secondary Service Area";
}

<script>
    $(document).ready(function () {

        $("#ServiceAreaId").html('<option>loading...</option>');

        GetServiceAreas();

        $("#StateId").change(function () {
            GetServiceAreas();
        });

        function GetServiceAreas() {

            $.getJSON("/ServiceArea/GetSecondaryServiceAreasByState", { stateId: $("#StateId").val(), contractorId: $("#ContractorId").val() },
                function (serviceAreas) {
                    $("#ServiceAreaId").empty();

                    $.each(serviceAreas, function (i, serviceArea) {
                        $("#ServiceAreaId").append(
                            $('<option/>')
                         .attr('value', this.ServiceAreaId)
                         .text(this.Name)
                        );
                    });

                    if (serviceAreas.length == 0) {
                        $("#ServiceAreaId").append(
                        $('<option/>')
                     .attr('value', 0)
                     .text('sorry, there are no service areas in this state')
                        );

                        $("input[type=submit").prop('disabled', true);
                    }

                    if (serviceAreas.length > 0) {
                        $("input[type=submit").prop('disabled', false);
                    }
                });
        }
    });
</script>

<h2>Add Secondary Service Area | <span class="contractor">@Html.ActionLink("back", "Index", new { id = Model.ContractorId }, new { @class = "contractor" })</span></h2>

<p>
    Select a secondary service area to add, if you need to charge more to cover travel expenses, indicate a price here that will be added to the customers total 
    upon checkout if they select one of your available services.
</p>

<p style="margin: 1em 0;">
    Do you offer services in a service area that isn't listed?<br />Click @Html.ActionLink("here", "Contact", "Admin", new { subject = "Service Area Request" }, new { @class = "contractor" })
    to make a request and an admin can make it available for selection.
</p>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    @Html.HiddenFor(m => m.ContractorId)
     
    <div class="editor-label">
        State
    </div>
        
    <div class="editor-field">
        @Html.DropDownList("StateId", (SelectList)ViewBag.State)
    </div>
    
    <div class="editor-label">
        Service Area
    </div>
        
    <div class="editor-field">
        @Html.DropDownListFor(m => m.ServiceAreaId, (SelectList)ViewBag.ServiceArea, "[ - select a service area - ]", new { style = "width: auto" })
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Price)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Price)
        @Html.ValidationMessageFor(model => model.Price)
    </div>

    <p>
        <input type="submit" value="Add" />
    </p>
}

Views/ContractorServiceArea/Delete.cshtml
@model YardLad.Models.Domain.ContractorServiceArea

@{
    ViewBag.Title = "Remove Secondary Service Area";
}

<h2>Remove Secondary Service Area | <span class="contractor">@Html.ActionLink("back", "Index", new { id = Model.ContractorId }, new { @class = "contractor" })</span></h2>
<h3>Are you sure you want to remove this?</h3>

@using (Html.BeginForm()) {
    <input type="submit" value="Delete" />
        
}

Views/ContractorServiceArea/Details.cshtml
@model YardLad.Models.Domain.ContractorServiceArea

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>ContractorServiceArea</legend>

    <div class="display-label">Contractor</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Contractor.Name)
    </div>

    <div class="display-label">ServiceArea</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ServiceArea.Name)
    </div>

    <div class="display-label">Price</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ContractorServiceAreaId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/ContractorServiceArea/Edit.cshtml
@model YardLad.Models.Domain.ContractorServiceArea

@{
    ViewBag.Title = "Edit Service Area";
}

<h2>Edit Service Area | <span class="contractor">@Html.ActionLink("back", "Index", new { id = Model.ContractorId }, new { @class = "contractor" })</span></h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    @Html.HiddenFor(model => model.ContractorServiceAreaId)

    <div class="editor-label">
        @Html.LabelFor(model => model.ContractorId, "Contractor")
    </div>
    <div class="editor-field">
        @Html.DropDownList("ContractorId", String.Empty)
        @Html.ValidationMessageFor(model => model.ContractorId)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.ServiceAreaId, "ServiceArea")
    </div>
    <div class="editor-field">
        @Html.DropDownList("ServiceAreaId", String.Empty)
        @Html.ValidationMessageFor(model => model.ServiceAreaId)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Price)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Price)
        @Html.ValidationMessageFor(model => model.Price)
    </div>

    <p>
        <input type="submit" value="Save" />
    </p>
}

Views/ContractorServiceArea/Index.cshtml
@model IEnumerable<YardLad.Models.Domain.ContractorServiceArea>

@{
    ViewBag.Title = "Index";
}

<h2>Secondary Service Areas | <span class="contractor">@Html.ActionLink("back", "MyAccount", "Account", null, new { @class = "contractor" })</span></h2>

<p>
    @Html.ActionLink("Add New", "Create", new { id = ViewBag.ContractorId }, new { @class = "contractor" })
</p>

<p>
    If you need to offer services outside your primary service area, you can add them here.
    You can set a price modifier when adding a new service area to help cover travel expenses. The total amount will be updated
    for a customer when they select a service you offer upon checkout.
</p>

<table class="display dataTable">
    <thead>
    <tr>
        <th>
            State
        </th>
        <th>
            Service Area
        </th>
        <th>
            Price
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.OrderBy(csa => csa.ServiceArea.State.Name).ThenBy(csa => csa.ServiceArea.Name)) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceArea.State.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceArea.Name)
            </td>
            <td>
                @item.Price.ToString("c")
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ContractorServiceAreaId }, new { @class = "contractor" }) |
                @Html.ActionLink("Remove", "Delete", new { id=item.ContractorServiceAreaId }, new { @class = "contractor" })
            </td>
        </tr>
    }
    </tbody>
</table>